#!/bin/bash
unset -f change-erlang-version
function change-erlang-version() {
  case "$1" in
    "20"|"20.3"|"21"|"21.3"|"22"|"22.3"|"23"|"23.0" )
        . /home/semaphore/.kerl/installs/$1/activate
    ;;
    * )
      echo "Please provide a valid Erlang version! [20|20.3|21|21.3|22|22.3|23|23.0]"
      return 1
    ;;
  esac

  echo "## Current Erlang version set to:"
  erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
}
